### ISSUE TITLE
Simulation of nested orbiting objects 

### ISSUE THREAD

**Issue by Trixter9994** [VirtualPlanetaryLaboratory/vplanet#92]
While adjusting a planet's inputs to take into account any orbiting bodies works in many situations, it does not take into account any tidal forces between the planet and the orbiting body or the orbiting body and the stellar body the planet itself is orbiting around. Basically, I'm looking for a way to easily create an array of orbiting bodies around any object that is already in its own orbit.

**Comment by RoryBarnes** [comment]
Currently VPLanet does *not* include tidal forces for bodies orbiting a body that orbits another body. For example, you cannot simulate the tidal evolution of Earth due to the Moon *and* Sun, only one or the other. You can simulate the tidal evolution of multiple bodies orbiting a single body (see e.g. the CassiniMulti example), and you can simulate a star-planet-moon system with SpiNBody (no example yet). So I don't think that VPLanet will simulate the systems you are interested in.

**Comment by Trixter9994** [comment]
That's a shame, I'll just hope for a future update that will hopefully add that in.
